import { Inter, Kanit } from "next/font/google";
import Header from "./header";

import './globals.css';

const inter = Inter({ subsets: ["latin"], variable: '--font-inter' });


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

//                 <div className="bg-default bg-blend-multiply opacity-100">
//                    <div className="background-gradient opacity-30">
//                        <div className="noise bg-blend-multiply opacity-75">

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="background-gradient">
                    <div className="bg-gradient-to-bl from-default/10 to-default/50 ">
                        <div className="h-screen w-screen opacity-100 flex items-center justify-center">
                            <Header />
                            <div className="absolute top-24 max-w-[75rem] mx-5 bg-red-500">
                                {children}
                            </div>
                        </div>
                    </div>
                </div>
            </body>
        </html >
    );
}
