
import { Inter } from "next/font/google";
import localFont from "next/font/local";

import { WavyBackground } from "./(components)/BackgroundWaves"
import BackgroundFill from "./(components)/BackgroundFill"
import Sidebar from "./(components)/Sidebar"
import Footer from "./(components)/Footer"
import ControlBar from "./(components)/controls/ControlBar"
import Providers from "./providers"

import './globals.css';
import Reveal from "./(components)/Reveal";

const inter = Inter({ subsets: ["latin"], variable: '--font-inter' });
const apercu = localFont({
    src: [
        {
            path: '../public/fonts/Apercu-Medium.otf',
            weight: '400'
        },
        {
            path: '../public/fonts/Apercu-Bold.otf',
            weight: '700'
        },
    ],
    variable: '--font-apercu'
})

const neuemachina = localFont({
    src: [
        {
            path: '../public/fonts/NeueMachina-Regular.otf',
            weight: '400'
        },
        {
            path: '../public/fonts/NeueMachina-Light.otf',
            weight: '300'

        },
        {
            path: '../public/fonts/NeueMachina-Ultrabold.otf',
            weight: '700'
        },
    ],
    variable: "--font-neuemachina"
})

export const metadata = {
    title: "Max Lafrance",
    description: "Generated by create next app",
};


export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning className={`${inter.className} ${apercu.className} ${neuemachina.className}`}>
            <body>
                <Providers>
                    <BackgroundFill />
                    <Reveal duration={4} delay={0.1}>
                        <WavyBackground />
                    </Reveal>
                    <div className="flex">
                        <Sidebar className="w-[300px] h-screen" />
                        {/** Main content section **/}
                        <div className="h-screen w-full p-8 overflow-y-auto z-10">
                            {children}
                            <ControlBar className="fixed top-2 right-6" />
                            <Footer />
                        </div>
                    </div>
                    <div className="static-noise pointer-events-none"></div>
                </Providers>
            </body>
        </html >
    );
}
